### ISSUE TITLE
flaky test in pkg/smi resulting in panic

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2108]
**Bug description**:
With the introduction of pubsub, it seems like some tests have become flaky. Noticed a test timeout due to panic from a failed CI run:
https://pipelines.actions.githubusercontent.com/FqYyUlFBwgcC4xlcAlRHSOZjGFqxSg5UdT6unwZ3oA6NkQIoht/_apis/pipelines/1/runs/7625/signedlogcontent/40?urlExpires=2020-11-20T23%3A36%3A04.2685328Z&urlSigningMethod=HMACV1&urlSignature=iYp0HOU21ndbGqh7DtKBp220DqmH2ijHFqwB5ctw8Y8%3D

```
11:29PM INF [SMI Client] Waiting for informers' cache to sync: TrafficSplit, HTTPRouteGroup, TCPRoute, TrafficTarget, Backpressure component=mesh-spec file=client.go:90
11:29PM INF [SMI Client] Cache sync finished for [TrafficSplit HTTPRouteGroup TCPRoute TrafficTarget Backpressure] component=mesh-spec file=client.go:98
11:29PM WRN Channel for provider SMI is full, dropping channel notify traffictarget-deleted  component=kube-controller file=event_handlers.go:61
coverage: 33.1% of statements
panic: test timed out after 2m0s

goroutine 243 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1618 +0xe5
created by time.goFunc
	/opt/hostedtoolcache/go/1.15.5/x64/src/time/sleep.go:167 +0x45

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc0000e7380, 0x17f264e, 0x7, 0x189d610, 0x497d26)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc0000e7200)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1439 +0x78
testing.tRunner(0xc0000e7200, 0xc0000cbda8)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1123 +0xef
testing.runTests(0xc00048ffa0, 0x24994a0, 0x1, 0x1, 0xbfe6324e53e90eb9, 0x1bf191e44f, 0x24d3ec0, 0x40f5b0)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1437 +0x2fe
testing.(*M).Run(0xc000247280, 0x0)
	/opt/hostedtoolcache/go/1.15.5/x64/src/testing/testing.go:1345 +0x1eb
main.main()
	_testmain.go:99 +0x1c5
```

```
2020-11-20T23:31:05.6008534Z goroutine 234 [select]:
2020-11-20T23:31:05.6009439Z k8s.io/client-go/tools/cache.(*processorListener).pop(0xc000247d00)
2020-11-20T23:31:05.6011145Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/shared_informer.go:709 +0x157
2020-11-20T23:31:05.6012045Z k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0000d3250, 0xc000552520)
2020-11-20T23:31:05.6013010Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:73 +0x51
2020-11-20T23:31:05.6013944Z created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
2020-11-20T23:31:05.6015153Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:71 +0x65
2020-11-20T23:31:05.6015941Z FAIL	github.com/openservicemesh/osm/pkg/smi	120.058s
2020-11-20T23:31:05.6016544Z === RUN   TestAllEqual
```

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X]
- CI System                  [ ]

**Comment by shashankram** [comment]
@eduser25 why do we have so many goroutines being launched?

```
2020-11-20T23:31:05.6008534Z goroutine 234 [select]:
2020-11-20T23:31:05.6009439Z k8s.io/client-go/tools/cache.(*processorListener).pop(0xc000247d00)
2020-11-20T23:31:05.6011145Z 	/home/runner/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/shared_informer.go:709 +0x157
2020-11-20T23:31:05.6012045Z k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0000d3250, 0xc000552520)
2020-11-20T23:31:05.6013010Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:73 +0x51
2020-11-20T23:31:05.6013944Z created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
2020-11-20T23:31:05.6015153Z 	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:71 +0x65
2020-11-20T23:31:05.6015941Z FAIL	github.com/openservicemesh/osm/pkg/smi	120.058s
2020-11-20T23:31:05.6016544Z === RUN   TestAllEqual
```
