### ISSUE TITLE
Race condition in multiple map writes

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#2441]
Unprotected xdsLog map `newAggregatedDiscoveryResponse` can cause multiple writes on the same map by multiple XDS streams.

```
if s.enableDebug {
	if _, ok := s.xdsLog[proxy.GetCertificateCommonName()]; !ok {
		s.xdsLog[proxy.GetCertificateCommonName()] = make(map[envoy.TypeURI][]time.Time)
	}
	s.xdsLog[proxy.GetCertificateCommonName()][typeURL] = append(s.xdsLog[proxy.GetCertificateCommonName()][typeURL], time.Now())
}
```

```
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=47958120135765980282011679423970448229 connected"}
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=292599240870444999781775540991616545771 connected"}
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=13976008947031965673617590686339049877 connected"}
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=325617134786043019829286577548510098552 connected"}
{"level":"warn","component":"envoy/ads","time":"2021-02-03T00:24:34Z","file":"stream.go:29","message":"Envoy with certificate SerialNumber=309609523710001943616120577866357811376 connected"}
fatal error: concurrent map writes

goroutine 786 [running]:
runtime.throw(0x1d48b66, 0x15)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0041bde68 sp=0xc0041bde38 pc=0x434ad2
runtime.mapassign_faststr(0x1a2edc0, 0xc0042a8360, 0xc003e17980, 0x38, 0x307b100)
        /usr/local/go/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc0041bded0 sp=0xc0041bde68 pc=0x413657
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).newAggregatedDiscoveryResponse(0xc003851020, 0xc003ed9500, 0xc000826e00, 0x208a8a0, 0xc0002ebef0, 0x3, 0xc003ee3920, 0xbffe99308f637c36)
        /home/eserra/src/osm/pkg/envoy/ads/response.go:136 +0xa6d fp=0xc0041be248 sp=0xc0041bded0 pc=0x182edad
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).sendTypeResponse(0xc003851020, 0x1d84958, 0x33, 0xc003ed9500, 0xc001cce4b0, 0xc000826e00, 0x208a8a0, 0xc0002ebef0, 0x0, 0x0)
        /home/eserra/src/osm/pkg/envoy/ads/response.go:30 +0x402 fp=0xc0041be730 sp=0xc0041be248 pc=0x182cab2
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).StreamAggregatedResources(0xc003851020, 0x207ce40, 0xc001cce4a0, 0x0, 0x0)
        /home/eserra/src/osm/pkg/envoy/ads/stream.go:164 +0x200b fp=0xc0041bfc18 sp=0xc0041be730 pc=0x183126b
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1bfb8c0, 0xc003851020, 0x2074920, 0xc0009e1d40, 0x3079530, 0xc00437c500)
        /home/eserra/src/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.8/envoy/service/discovery/v3/ads.pb.go:298 +0xad fp=0xc0041bfc60 sp=0xc0041bfc18 pc=0x16f00fd
google.golang.org/grpc.(*Server).processStreamingRPC(0xc003b18c00, 0x2081d60, 0xc003efe780, 0xc00437c500, 0xc0042a8b10, 0x302e820, 0x0, 0x0, 0x0)
        /home/eserra/src/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1237 +0xcd1 fp=0xc0041bfe38 sp=0xc0041bfc60 pc=0x16dd5f1
google.golang.org/grpc.(*Server).handleStream(0xc003b18c00, 0x2081d60, 0xc003efe780, 0xc00437c500, 0x0)
        /home/eserra/src/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1317 +0xcd6 fp=0xc0041bff68 sp=0xc0041bfe38 pc=0x16dee26
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000e2d830, 0xc003b18c00, 0x2081d60, 0xc003efe780, 0xc00437c500)
        /home/eserra/src/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xa1 fp=0xc0041bffb8 sp=0xc0041bff68 pc=0x16ebac1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0041bffc0 sp=0xc0041bffb8 pc=0x467691
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/eserra/src/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa1
```

**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by eduser25** [comment]
This one is easy to hit with quite some pods and a restarting OSM, as all of them will attempt to reconnect at the same time, causing updates for all of them (hence easily triggering the race).
