### ISSUE TITLE
docs: search is not working

### ISSUE THREAD

**Issue by sozercan** [openservicemesh/osm#2521]
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Docs                       [x]

**Expected behavior**:

Search is not working in the docs website

Seeing this error in console, that might be related:

```
jquery-3.5.1.min.js:2 jQuery.Deferred exception: Bootstrap tooltips require Popper.js (https://popper.js.org) TypeError: Bootstrap tooltips require Popper.js (https://popper.js.org)
    at i (https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:6:32531)
    at new i (https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:6:41659)
    at HTMLInputElement.<anonymous> (https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:6:42663)
    at Function.each (https://code.jquery.com/jquery-3.5.1.min.js:2:2976)
    at S.fn.init.each (https://code.jquery.com/jquery-3.5.1.min.js:2:1454)
    at S.fn.init.i._jQueryInterface [as popover] (https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js:6:42555)
    at render (https://docs.openservicemesh.io/js/main.min.664f21bf5eb0c31ebc661e2616e6c63e0448cec6d5636d869957be423c3cb952.js:5:1740)
    at HTMLInputElement.<anonymous> (https://docs.openservicemesh.io/js/main.min.664f21bf5eb0c31ebc661e2616e6c63e0448cec6d5636d869957be423c3cb952.js:5:1234)
    at HTMLInputElement.dispatch (https://code.jquery.com/jquery-3.5.1.min.js:2:43090)
    at HTMLInputElement.v.handle (https://code.jquery.com/jquery-3.5.1.min.js:2:41074) undefined
```

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

cc @flynnduism

**Comment by shashankram** [comment]
Resolved in https://github.com/openservicemesh/osm-docs/issues/4.
